version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    container_name: postgresdb
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmincon
    restart: always
    depends_on:
      - "postgres"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: info@info.com
      ## Replace with your email
      PGADMIN_DEFAULT_PASSWORD: admin
      
  graphql-engine:
    image: hasura/graphql-engine:v2.8.4
    container_name: hasuraengine
    ports:
    - "8081:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      ## HASURA_GRAPHQL_ADMIN_SECRET: admin_secret
volumes:
  db_data:
